/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios_Tema10_Barco_Vista;

import Ejercicios_Tema10_Barco_DAO.ImplementacionDAOObjectStream;
import Ejercicios_Tema10_Barco_Modelo.Barco;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author VESPERTINO
 */
public class BarcoJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarcoJInternalFrame
     */
    public BarcoJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlta = new javax.swing.JPanel();
        jPanelNorteAlta = new javax.swing.JPanel();
        jButtonAltaAlta = new javax.swing.JButton();
        jButtonAltaBaja = new javax.swing.JButton();
        jButtonAltaModificar = new javax.swing.JButton();
        jButtonAltaConsulta = new javax.swing.JButton();
        jPanelCentroAlta = new javax.swing.JPanel();
        jLabelMatriculaAlta = new javax.swing.JLabel();
        jTextFieldMatriculaAlta = new javax.swing.JTextField();
        jLabelEsloraAlta = new javax.swing.JLabel();
        jTextFieldEsloraAlta = new javax.swing.JTextField();
        jLabelYearFabricacionAlta = new javax.swing.JLabel();
        jTextFieldYearFabricacionAlta = new javax.swing.JTextField();
        jLabelPrecioAlta = new javax.swing.JLabel();
        jTextFieldPrecioAlta = new javax.swing.JTextField();
        jLabelNombreAlta = new javax.swing.JLabel();
        jTextFieldNombreAlta = new javax.swing.JTextField();
        jLabelMangaAlta = new javax.swing.JLabel();
        jTextFieldMangaAlta = new javax.swing.JTextField();
        jPanelSurAlta = new javax.swing.JPanel();
        jButtonAltaAtras = new javax.swing.JButton();
        jButtonAltaAceptar = new javax.swing.JButton();
        jButtonAltaAdelante = new javax.swing.JButton();
        jPanelBaja = new javax.swing.JPanel();
        jPanelNorteBaja = new javax.swing.JPanel();
        jButtonBajaAlta = new javax.swing.JButton();
        jButtonBajaBaja = new javax.swing.JButton();
        jButtonBajaModificar = new javax.swing.JButton();
        jButtonBajaConsultar = new javax.swing.JButton();
        jPanelCentroBaja = new javax.swing.JPanel();
        jLabelDniBaja = new javax.swing.JLabel();
        jTextFieldDniBaja = new javax.swing.JTextField();
        jPanelSurBaja = new javax.swing.JPanel();
        jButtonBajaAtras = new javax.swing.JButton();
        jButtonBajaAdelante = new javax.swing.JButton();
        jButtonBajaAceptar = new javax.swing.JButton();
        jPanelModificar = new javax.swing.JPanel();
        jPanelNorteModificar = new javax.swing.JPanel();
        jButtonModificarAlta = new javax.swing.JButton();
        jButtonModificarBaja = new javax.swing.JButton();
        jButtonModificarModificar = new javax.swing.JButton();
        jButtonModificarConsulta = new javax.swing.JButton();
        jPanelCentroModificar = new javax.swing.JPanel();
        jLabelDniModificar = new javax.swing.JLabel();
        jTextFieldDniModificar = new javax.swing.JTextField();
        jPanelSurModificar = new javax.swing.JPanel();
        jButtonModicarAtras = new javax.swing.JButton();
        jButtonModicarAdelante = new javax.swing.JButton();
        jButtonModicarAceptar = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelNorteConsulta = new javax.swing.JPanel();
        jButtonConsultaAlta = new javax.swing.JButton();
        jButtonConsultaBaja = new javax.swing.JButton();
        jButtonConsultaModifcar = new javax.swing.JButton();
        jButtonConsultaConsulta = new javax.swing.JButton();
        jPanelCentroConsulta = new javax.swing.JPanel();
        jScrollPaneConsulta = new javax.swing.JScrollPane();
        jTextFieldConsulta = new javax.swing.JTextField();
        jPanelSurConsulta = new javax.swing.JPanel();
        jButtonConsultaAtras = new javax.swing.JButton();
        jButtonConsultaAdelante = new javax.swing.JButton();
        jButtonConsultaAceptar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelAlta.setLayout(new java.awt.BorderLayout());

        jButtonAltaAlta.setText("ALTA");
        jButtonAltaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAltaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaAlta);

        jButtonAltaBaja.setText("BAJA");
        jButtonAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaBajaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaBaja);

        jButtonAltaModificar.setText("MODIFICACION");
        jButtonAltaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaModificarActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaModificar);

        jButtonAltaConsulta.setText("CONSULTA");
        jButtonAltaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaConsultaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaConsulta);

        jPanelAlta.add(jPanelNorteAlta, java.awt.BorderLayout.NORTH);

        jPanelCentroAlta.setLayout(new java.awt.GridLayout(6, 2));

        jLabelMatriculaAlta.setText("MATRICULA");
        jPanelCentroAlta.add(jLabelMatriculaAlta);

        jTextFieldMatriculaAlta.setText("                                                              ");
        jTextFieldMatriculaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldMatriculaAlta);

        jLabelEsloraAlta.setText("ESLORA METROS");
        jPanelCentroAlta.add(jLabelEsloraAlta);

        jTextFieldEsloraAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldEsloraAlta);

        jLabelYearFabricacionAlta.setText("AÑO FABRICACION");
        jPanelCentroAlta.add(jLabelYearFabricacionAlta);

        jTextFieldYearFabricacionAlta.setText("                                                              ");
        jTextFieldYearFabricacionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYearFabricacionAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldYearFabricacionAlta);

        jLabelPrecioAlta.setText("PRECIO");
        jPanelCentroAlta.add(jLabelPrecioAlta);

        jTextFieldPrecioAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldPrecioAlta);

        jLabelNombreAlta.setText("NOMBRE");
        jPanelCentroAlta.add(jLabelNombreAlta);

        jTextFieldNombreAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldNombreAlta);

        jLabelMangaAlta.setText("MANGA METROS");
        jPanelCentroAlta.add(jLabelMangaAlta);

        jTextFieldMangaAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldMangaAlta);

        jPanelAlta.add(jPanelCentroAlta, java.awt.BorderLayout.CENTER);

        jButtonAltaAtras.setText("ATRAS");
        jButtonAltaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAtrasActionPerformed(evt);
            }
        });

        jButtonAltaAceptar.setText("ACEPTAR");
        jButtonAltaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAceptarActionPerformed(evt);
            }
        });

        jButtonAltaAdelante.setText("ADELANTE");
        jButtonAltaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSurAltaLayout = new javax.swing.GroupLayout(jPanelSurAlta);
        jPanelSurAlta.setLayout(jPanelSurAltaLayout);
        jPanelSurAltaLayout.setHorizontalGroup(
            jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSurAltaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonAltaAtras)
                .addGap(18, 18, 18)
                .addComponent(jButtonAltaAdelante)
                .addGap(26, 26, 26)
                .addComponent(jButtonAltaAceptar)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelSurAltaLayout.setVerticalGroup(
            jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSurAltaLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltaAtras)
                    .addComponent(jButtonAltaAdelante)
                    .addComponent(jButtonAltaAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlta.add(jPanelSurAlta, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelAlta, "card6");

        jPanelBaja.setLayout(new java.awt.BorderLayout());

        jButtonBajaAlta.setText("ALTA");
        jButtonBajaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAltaActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaAlta);

        jButtonBajaBaja.setText("BAJA");
        jButtonBajaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaBajaActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaBaja);

        jButtonBajaModificar.setText("MODIFICACION");
        jButtonBajaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaModificarActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaModificar);

        jButtonBajaConsultar.setText("CONSULTA");
        jButtonBajaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaConsultarActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaConsultar);

        jPanelBaja.add(jPanelNorteBaja, java.awt.BorderLayout.NORTH);

        jLabelDniBaja.setText("PON LA MATRICULA DEL BARCO QUE QUIERAS ELIMINAR : ");

        jTextFieldDniBaja.setText("                                                    ");

        javax.swing.GroupLayout jPanelCentroBajaLayout = new javax.swing.GroupLayout(jPanelCentroBaja);
        jPanelCentroBaja.setLayout(jPanelCentroBajaLayout);
        jPanelCentroBajaLayout.setHorizontalGroup(
            jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                .addGroup(jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelDniBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jTextFieldDniBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelCentroBajaLayout.setVerticalGroup(
            jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelDniBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextFieldDniBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanelBaja.add(jPanelCentroBaja, java.awt.BorderLayout.CENTER);

        jButtonBajaAtras.setText("ATRAS");
        jButtonBajaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAtrasActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAtras);

        jButtonBajaAdelante.setText("ADELANTE");
        jButtonBajaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAdelanteActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAdelante);

        jButtonBajaAceptar.setText("ACEPTAR");
        jButtonBajaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAceptarActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAceptar);

        jPanelBaja.add(jPanelSurBaja, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelBaja, "card5");

        jPanelModificar.setLayout(new java.awt.BorderLayout());

        jButtonModificarAlta.setText("ALTA");
        jButtonModificarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAltaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarAlta);

        jButtonModificarBaja.setText("BAJA");
        jButtonModificarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarBajaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarBaja);

        jButtonModificarModificar.setText("MODIFICACION");
        jButtonModificarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarModificarActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarModificar);

        jButtonModificarConsulta.setText("CONSULTA");
        jButtonModificarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarConsultaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarConsulta);

        jPanelModificar.add(jPanelNorteModificar, java.awt.BorderLayout.NORTH);

        jLabelDniModificar.setText("PON LA MATRICULA DEL BARCO QUE QUIERAS MODIFICAR : ");

        jTextFieldDniModificar.setText("                                             ");

        javax.swing.GroupLayout jPanelCentroModificarLayout = new javax.swing.GroupLayout(jPanelCentroModificar);
        jPanelCentroModificar.setLayout(jPanelCentroModificarLayout);
        jPanelCentroModificarLayout.setHorizontalGroup(
            jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                .addGroup(jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelDniModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jTextFieldDniModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelCentroModificarLayout.setVerticalGroup(
            jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelDniModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jTextFieldDniModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanelModificar.add(jPanelCentroModificar, java.awt.BorderLayout.CENTER);

        jButtonModicarAtras.setText("ATRAS");
        jButtonModicarAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAtrasActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAtras);

        jButtonModicarAdelante.setText("ADELANTE");
        jButtonModicarAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAdelanteActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAdelante);

        jButtonModicarAceptar.setText("ACEPTAR");
        jButtonModicarAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAceptarActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAceptar);

        jPanelModificar.add(jPanelSurModificar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelModificar, "card4");

        jPanelConsulta.setLayout(new java.awt.BorderLayout());

        jButtonConsultaAlta.setText("ALTA");
        jButtonConsultaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAltaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaAlta);

        jButtonConsultaBaja.setText("BAJA");
        jButtonConsultaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaBajaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaBaja);

        jButtonConsultaModifcar.setText("MODIFICACION");
        jButtonConsultaModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaModifcarActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaModifcar);

        jButtonConsultaConsulta.setText("CONSULTA");
        jButtonConsultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaConsultaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaConsulta);

        jPanelConsulta.add(jPanelNorteConsulta, java.awt.BorderLayout.NORTH);

        jScrollPaneConsulta.setViewportView(jTextFieldConsulta);

        javax.swing.GroupLayout jPanelCentroConsultaLayout = new javax.swing.GroupLayout(jPanelCentroConsulta);
        jPanelCentroConsulta.setLayout(jPanelCentroConsultaLayout);
        jPanelCentroConsultaLayout.setHorizontalGroup(
            jPanelCentroConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroConsultaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelCentroConsultaLayout.setVerticalGroup(
            jPanelCentroConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelConsulta.add(jPanelCentroConsulta, java.awt.BorderLayout.CENTER);

        jButtonConsultaAtras.setText("ATRAS");
        jButtonConsultaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAtrasActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAtras);

        jButtonConsultaAdelante.setText("ADELANTE");
        jButtonConsultaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAdelanteActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAdelante);

        jButtonConsultaAceptar.setText("ACEPTAR");
        jButtonConsultaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAceptarActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAceptar);

        jPanelConsulta.add(jPanelSurConsulta, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelConsulta, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMatriculaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaAltaActionPerformed

    private void jTextFieldYearFabricacionAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYearFabricacionAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearFabricacionAltaActionPerformed

    private void jButtonAltaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());        
        cl.show(getContentPane(), "card6");           
    }//GEN-LAST:event_jButtonAltaAltaActionPerformed

    private void jButtonBajaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           

    }//GEN-LAST:event_jButtonBajaAltaActionPerformed

    private void jButtonModificarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           

    }//GEN-LAST:event_jButtonModificarAltaActionPerformed

    private void jButtonConsultaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           
    }//GEN-LAST:event_jButtonConsultaAltaActionPerformed

    private void jButtonAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");           
        
    }//GEN-LAST:event_jButtonAltaBajaActionPerformed

    private void jButtonBajaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");           
    }//GEN-LAST:event_jButtonBajaBajaActionPerformed

    private void jButtonModificarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");                  
    }//GEN-LAST:event_jButtonModificarBajaActionPerformed

    private void jButtonConsultaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");                  
    }//GEN-LAST:event_jButtonConsultaBajaActionPerformed

    private void jButtonAltaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonAltaModificarActionPerformed

    private void jButtonBajaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");                  
    }//GEN-LAST:event_jButtonBajaModificarActionPerformed

    private void jButtonModificarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonModificarModificarActionPerformed

    private void jButtonConsultaModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaModifcarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonConsultaModifcarActionPerformed

    private void jButtonAltaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonAltaConsultaActionPerformed

    private void jButtonBajaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaConsultarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");           
    }//GEN-LAST:event_jButtonBajaConsultarActionPerformed

    private void jButtonModificarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonModificarConsultaActionPerformed

    private void jButtonConsultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonConsultaConsultaActionPerformed

    private void jButtonConsultaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonConsultaAtrasActionPerformed

    private void jButtonBajaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonBajaAtrasActionPerformed

    private void jButtonModicarAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonModicarAtrasActionPerformed

    private void jButtonAltaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
            cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonAltaAtrasActionPerformed

    private void jButtonAltaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonAltaAdelanteActionPerformed

    private void jButtonBajaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonBajaAdelanteActionPerformed

    private void jButtonModicarAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonModicarAdelanteActionPerformed

    private void jButtonConsultaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonConsultaAdelanteActionPerformed
    //metodo añadir barco
    private void jButtonAltaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAceptarActionPerformed
        try{
        //creamos un barco auxiliar con los datos pasados en JTEXTFIELD
        esRequerido(jTextFieldMatriculaAlta.getText(), " matricula");
            String matricula = jTextFieldMatriculaAlta.getText();
            int esloraMetros = Integer.parseInt(jTextFieldEsloraAlta.getText());
            int yearFabricacion = Integer.parseInt(jTextFieldYearFabricacionAlta.getText());
            double precio = Double.parseDouble(jTextFieldPrecioAlta.getText());
            String nombre = jTextFieldNombreAlta.getText();
            int mangaMetros = Integer.parseInt(jTextFieldMangaAlta.getText());
            Barco auxBarco = new Barco(matricula, esloraMetros, yearFabricacion, precio, nombre, mangaMetros);
          
            if (cursor.darAltaBarco(auxBarco)) {
                JOptionPane.showMessageDialog(this, "Barco añadido con exito", "OK", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe el barco con esta matricula", "Error", 2);
            }
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Los campos matricula y eslora deben ser numeros enteros");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"En estos momentos no se puede realizar la operacion");
        }
    }//GEN-LAST:event_jButtonAltaAceptarActionPerformed
    //metodo borrar barco
    private void jButtonBajaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAceptarActionPerformed
                int matricula = Integer.parseInt(jTextFieldDniBaja.getText());
                Barco auxCliente = new Barco(jTextFieldDniBaja.getText());
                //si el cliente existe
                if (cursor.darBajaBarco(auxCliente)) {
                    JOptionPane.showMessageDialog(this, "Cliente borrado con exito", "OK", 1);
                } else {
                    JOptionPane.showMessageDialog(this, "No existe el cliente con este DNI", "Error", 2);
                }
    }//GEN-LAST:event_jButtonBajaAceptarActionPerformed
    //metodo modificar barco
    private void jButtonModicarAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAceptarActionPerformed
            String matricula = jTextFieldDniModificar.getText();
            Barco viejo= new Barco(matricula);
            if(viejo==null){
                JOptionPane.showMessageDialog(this, "No existe ese barco.");
            }else{
                //datos nuevos pdiendolos por la ventana
                jLabelMatriculaAlta.setText("Nueva Matricula:");
                jLabelEsloraAlta.setText("Nueva Eslora:");
                jLabelYearFabricacionAlta.setText("Nuevo año de fabricación:");
                jLabelPrecioAlta.setText("Nuevo Precio:");
                jLabelNombreAlta.setText("Nuevo Nombre:");
                jLabelMangaAlta.setText("Nuevo Manga:");
                //escribimos los datos
                String matriculaNueva = jTextFieldMatriculaAlta.getText();
                int esloraMetrosNueva = Integer.parseInt(jTextFieldEsloraAlta.getText());
                int yearFabricacionNueva = Integer.parseInt(jTextFieldYearFabricacionAlta.getText());
                double precioNueva = Double.parseDouble(jTextFieldPrecioAlta.getText());
                String nombreNueva = jTextFieldNombreAlta.getText();
                int mangaMetrosNueva = Integer.parseInt(jTextFieldMangaAlta.getText());

                //creamos el objeto nuevo
                Barco nuevo = new Barco(matriculaNueva,esloraMetrosNueva ,yearFabricacionNueva,
                precioNueva,nombreNueva,mangaMetrosNueva );
                //llamamos al metodo modificar
                if(cursor.modificarBarco(viejo, nuevo)==true){
                    cursor.modificarBarco(viejo, nuevo);
                    JOptionPane.showMessageDialog(this,"Barco modificado.");
                }
            }
    }//GEN-LAST:event_jButtonModicarAceptarActionPerformed
    //metodo consultar barcos
    private void jButtonConsultaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAceptarActionPerformed
        //jScrollPaneConsulta.settext(cursor.recorrerBarco());
        //escribimos los datos
//                String matricula = jTextFieldMatriculaAlta.getText();
//                int esloraMetros = Integer.parseInt(jTextFieldEsloraAlta.getText());
//                int yearFabricacion = Integer.parseInt(jTextFieldYearFabricacionAlta.getText());
//                double precio= Double.parseDouble(jTextFieldPrecioAlta.getText());
//                String nombre = jTextFieldNombreAlta.getText();
//                int mangaMetros = Integer.parseInt(jTextFieldMangaAlta.getText());
//        Barco auxBarco = new Barco(matricula, esloraMetros, yearFabricacion, precio, nombre, mangaMetros);
//        jScrollPaneConsulta = new JScrollPane(jTextFieldConsulta);
//        
//        jTextFieldConsulta.setText(cursor.recorrerBarco(auxBarco));
//        jPanelCentroConsulta.add(jTextFieldConsulta);
//        jScrollPaneConsulta.setVisible(false);
    }//GEN-LAST:event_jButtonConsultaAceptarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
        cursor.salvarBarco("FicheroBarcos");
    }                                        

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {                                         
        try{
            cursor.cargarBarco("FicheroBarcos");
        }catch(NullPointerException n){
            System.out.println(n.getMessage());
        }
    } 
    
    private void esRequerido(String dato, String nombreCampo) {
        if (dato.equals("")) {
            JOptionPane.showMessageDialog(this, "El campo " + nombreCampo + " es requerido");
            
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaAceptar;
    private javax.swing.JButton jButtonAltaAdelante;
    private javax.swing.JButton jButtonAltaAlta;
    private javax.swing.JButton jButtonAltaAtras;
    private javax.swing.JButton jButtonAltaBaja;
    private javax.swing.JButton jButtonAltaConsulta;
    private javax.swing.JButton jButtonAltaModificar;
    private javax.swing.JButton jButtonBajaAceptar;
    private javax.swing.JButton jButtonBajaAdelante;
    private javax.swing.JButton jButtonBajaAlta;
    private javax.swing.JButton jButtonBajaAtras;
    private javax.swing.JButton jButtonBajaBaja;
    private javax.swing.JButton jButtonBajaConsultar;
    private javax.swing.JButton jButtonBajaModificar;
    private javax.swing.JButton jButtonConsultaAceptar;
    private javax.swing.JButton jButtonConsultaAdelante;
    private javax.swing.JButton jButtonConsultaAlta;
    private javax.swing.JButton jButtonConsultaAtras;
    private javax.swing.JButton jButtonConsultaBaja;
    private javax.swing.JButton jButtonConsultaConsulta;
    private javax.swing.JButton jButtonConsultaModifcar;
    private javax.swing.JButton jButtonModicarAceptar;
    private javax.swing.JButton jButtonModicarAdelante;
    private javax.swing.JButton jButtonModicarAtras;
    private javax.swing.JButton jButtonModificarAlta;
    private javax.swing.JButton jButtonModificarBaja;
    private javax.swing.JButton jButtonModificarConsulta;
    private javax.swing.JButton jButtonModificarModificar;
    private javax.swing.JLabel jLabelDniBaja;
    private javax.swing.JLabel jLabelDniModificar;
    private javax.swing.JLabel jLabelEsloraAlta;
    private javax.swing.JLabel jLabelMangaAlta;
    private javax.swing.JLabel jLabelMatriculaAlta;
    private javax.swing.JLabel jLabelNombreAlta;
    private javax.swing.JLabel jLabelPrecioAlta;
    private javax.swing.JLabel jLabelYearFabricacionAlta;
    private javax.swing.JPanel jPanelAlta;
    private javax.swing.JPanel jPanelBaja;
    private javax.swing.JPanel jPanelCentroAlta;
    private javax.swing.JPanel jPanelCentroBaja;
    private javax.swing.JPanel jPanelCentroConsulta;
    private javax.swing.JPanel jPanelCentroModificar;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JPanel jPanelNorteAlta;
    private javax.swing.JPanel jPanelNorteBaja;
    private javax.swing.JPanel jPanelNorteConsulta;
    private javax.swing.JPanel jPanelNorteModificar;
    private javax.swing.JPanel jPanelSurAlta;
    private javax.swing.JPanel jPanelSurBaja;
    private javax.swing.JPanel jPanelSurConsulta;
    private javax.swing.JPanel jPanelSurModificar;
    private javax.swing.JScrollPane jScrollPaneConsulta;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldDniBaja;
    private javax.swing.JTextField jTextFieldDniModificar;
    private javax.swing.JTextField jTextFieldEsloraAlta;
    private javax.swing.JTextField jTextFieldMangaAlta;
    private javax.swing.JTextField jTextFieldMatriculaAlta;
    private javax.swing.JTextField jTextFieldNombreAlta;
    private javax.swing.JTextField jTextFieldPrecioAlta;
    private javax.swing.JTextField jTextFieldYearFabricacionAlta;
    // End of variables declaration//GEN-END:variables
    ImplementacionDAOObjectStream cursor = new ImplementacionDAOObjectStream();

}
