/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios_Tema11_Conexion;



import java.awt.CardLayout;
import java.lang.invoke.MethodHandles;
import javax.swing.JOptionPane;


/**
 *
 * @author VESPERTINO
 */
public class VelerosJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarcoJInternalFrame
     */
    public VelerosJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlta = new javax.swing.JPanel();
        jPanelNorteAlta = new javax.swing.JPanel();
        jButtonAltaAlta = new javax.swing.JButton();
        jButtonAltaBaja = new javax.swing.JButton();
        jButtonAltaModificar = new javax.swing.JButton();
        jButtonAltaConsulta = new javax.swing.JButton();
        jPanelCentroAlta = new javax.swing.JPanel();
        jLabelMatriculaAlta = new javax.swing.JLabel();
        jTextFieldMatriculaAlta = new javax.swing.JTextField();
        jLabelMaterialConstruccionAlta = new javax.swing.JLabel();
        jTextFieldlMaterialConstruccionAlta = new javax.swing.JTextField();
        jLabelDescripcionAlta = new javax.swing.JLabel();
        jTextFieldlDescripcionAlta = new javax.swing.JTextField();
        jLabelEsloraAlta = new javax.swing.JLabel();
        jTextFieldEsloraAlta = new javax.swing.JTextField();
        jLabelMangaAlta = new javax.swing.JLabel();
        jTextFieldMangaAlta = new javax.swing.JTextField();
        jLabelPuntalAlta = new javax.swing.JLabel();
        jTextFieldlPuntalAlta = new javax.swing.JTextField();
        jLabelTripulacionMaximaAlta = new javax.swing.JLabel();
        jTextFieldTripulacionMaximaAlta = new javax.swing.JTextField();
        jLabelYearFabricacionAlta = new javax.swing.JLabel();
        jTextFieldYearFabricacionAlta = new javax.swing.JTextField();
        jLabelNumMasAlta = new javax.swing.JLabel();
        jTextFieldNumMasAlta = new javax.swing.JTextField();
        jLabelClaseVeleroAlta = new javax.swing.JLabel();
        jTextFieldClaseVeleroAlta = new javax.swing.JTextField();
        jPanelSurAlta = new javax.swing.JPanel();
        jButtonAltaAtras = new javax.swing.JButton();
        jButtonAltaAceptar = new javax.swing.JButton();
        jButtonAltaAdelante = new javax.swing.JButton();
        jPanelBaja = new javax.swing.JPanel();
        jPanelNorteBaja = new javax.swing.JPanel();
        jButtonBajaAlta = new javax.swing.JButton();
        jButtonBajaBaja = new javax.swing.JButton();
        jButtonBajaModificar = new javax.swing.JButton();
        jButtonBajaConsultar = new javax.swing.JButton();
        jPanelCentroBaja = new javax.swing.JPanel();
        jLabelMatriculaBaja = new javax.swing.JLabel();
        jTextFieldMatriculaBaja = new javax.swing.JTextField();
        jPanelSurBaja = new javax.swing.JPanel();
        jButtonBajaAtras = new javax.swing.JButton();
        jButtonBajaAdelante = new javax.swing.JButton();
        jButtonBajaAceptar = new javax.swing.JButton();
        jPanelModificar = new javax.swing.JPanel();
        jPanelNorteModificar = new javax.swing.JPanel();
        jButtonModificarAlta = new javax.swing.JButton();
        jButtonModificarBaja = new javax.swing.JButton();
        jButtonModificarModificar = new javax.swing.JButton();
        jButtonModificarConsulta = new javax.swing.JButton();
        jPanelCentroModificar = new javax.swing.JPanel();
        jLabelMatriculaModificar = new javax.swing.JLabel();
        jTextFieldMatriculaModificar = new javax.swing.JTextField();
        jPanelSurModificar = new javax.swing.JPanel();
        jButtonModicarAtras = new javax.swing.JButton();
        jButtonModicarAdelante = new javax.swing.JButton();
        jButtonModicarAceptar = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelNorteConsulta = new javax.swing.JPanel();
        jButtonConsultaAlta = new javax.swing.JButton();
        jButtonConsultaBaja = new javax.swing.JButton();
        jButtonConsultaModifcar = new javax.swing.JButton();
        jButtonConsultaConsulta = new javax.swing.JButton();
        jPanelCentroConsulta = new javax.swing.JPanel();
        jScrollPaneConsulta = new javax.swing.JScrollPane();
        jTextFieldConsulta = new javax.swing.JTextField();
        jPanelSurConsulta = new javax.swing.JPanel();
        jButtonConsultaAtras = new javax.swing.JButton();
        jButtonConsultaAdelante = new javax.swing.JButton();
        jButtonConsultaAceptar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelAlta.setLayout(new java.awt.BorderLayout());

        jButtonAltaAlta.setText("ALTA");
        jButtonAltaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAltaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaAlta);

        jButtonAltaBaja.setText("BAJA");
        jButtonAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaBajaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaBaja);

        jButtonAltaModificar.setText("MODIFICACION");
        jButtonAltaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaModificarActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaModificar);

        jButtonAltaConsulta.setText("CONSULTA");
        jButtonAltaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaConsultaActionPerformed(evt);
            }
        });
        jPanelNorteAlta.add(jButtonAltaConsulta);

        jPanelAlta.add(jPanelNorteAlta, java.awt.BorderLayout.NORTH);

        jPanelCentroAlta.setLayout(new java.awt.GridLayout(10, 2));

        jLabelMatriculaAlta.setText("MATRICULA");
        jPanelCentroAlta.add(jLabelMatriculaAlta);

        jTextFieldMatriculaAlta.setText("                                                              ");
        jTextFieldMatriculaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldMatriculaAlta);

        jLabelMaterialConstruccionAlta.setText("MATERIAL CONSTRUCCION");
        jPanelCentroAlta.add(jLabelMaterialConstruccionAlta);

        jTextFieldlMaterialConstruccionAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldlMaterialConstruccionAlta);

        jLabelDescripcionAlta.setText("DESCRIPCION");
        jPanelCentroAlta.add(jLabelDescripcionAlta);

        jTextFieldlDescripcionAlta.setText("                                                              ");
        jTextFieldlDescripcionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlDescripcionAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldlDescripcionAlta);

        jLabelEsloraAlta.setText("ESLORA");
        jPanelCentroAlta.add(jLabelEsloraAlta);

        jTextFieldEsloraAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldEsloraAlta);

        jLabelMangaAlta.setText("MANGA");
        jPanelCentroAlta.add(jLabelMangaAlta);

        jTextFieldMangaAlta.setText("                                                              ");
        jPanelCentroAlta.add(jTextFieldMangaAlta);

        jLabelPuntalAlta.setText("PUNTAL");
        jPanelCentroAlta.add(jLabelPuntalAlta);

        jTextFieldlPuntalAlta.setText("                                                              ");
        jTextFieldlPuntalAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlPuntalAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldlPuntalAlta);

        jLabelTripulacionMaximaAlta.setText("TRIPULACION MAXIMA");
        jPanelCentroAlta.add(jLabelTripulacionMaximaAlta);

        jTextFieldTripulacionMaximaAlta.setText("                                                           ");
        jTextFieldTripulacionMaximaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTripulacionMaximaAltaActionPerformed(evt);
            }
        });
        jPanelCentroAlta.add(jTextFieldTripulacionMaximaAlta);

        jLabelYearFabricacionAlta.setText("AÑO FABRICACION");
        jPanelCentroAlta.add(jLabelYearFabricacionAlta);

        jTextFieldYearFabricacionAlta.setText("                                               ");
        jPanelCentroAlta.add(jTextFieldYearFabricacionAlta);

        jLabelNumMasAlta.setText("NUMERO MASTIL");
        jPanelCentroAlta.add(jLabelNumMasAlta);

        jTextFieldNumMasAlta.setText("                                              ");
        jPanelCentroAlta.add(jTextFieldNumMasAlta);

        jLabelClaseVeleroAlta.setText("CLASE VELERO");
        jPanelCentroAlta.add(jLabelClaseVeleroAlta);

        jTextFieldClaseVeleroAlta.setText("                                              ");
        jPanelCentroAlta.add(jTextFieldClaseVeleroAlta);

        jPanelAlta.add(jPanelCentroAlta, java.awt.BorderLayout.CENTER);

        jButtonAltaAtras.setText("ATRAS");
        jButtonAltaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAtrasActionPerformed(evt);
            }
        });

        jButtonAltaAceptar.setText("ACEPTAR");
        jButtonAltaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAceptarActionPerformed(evt);
            }
        });

        jButtonAltaAdelante.setText("ADELANTE");
        jButtonAltaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSurAltaLayout = new javax.swing.GroupLayout(jPanelSurAlta);
        jPanelSurAlta.setLayout(jPanelSurAltaLayout);
        jPanelSurAltaLayout.setHorizontalGroup(
            jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSurAltaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonAltaAtras)
                .addGap(18, 18, 18)
                .addComponent(jButtonAltaAdelante)
                .addGap(26, 26, 26)
                .addComponent(jButtonAltaAceptar)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelSurAltaLayout.setVerticalGroup(
            jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSurAltaLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanelSurAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltaAtras)
                    .addComponent(jButtonAltaAdelante)
                    .addComponent(jButtonAltaAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlta.add(jPanelSurAlta, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelAlta, "card6");

        jPanelBaja.setLayout(new java.awt.BorderLayout());

        jButtonBajaAlta.setText("ALTA");
        jButtonBajaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAltaActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaAlta);

        jButtonBajaBaja.setText("BAJA");
        jButtonBajaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaBajaActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaBaja);

        jButtonBajaModificar.setText("MODIFICACION");
        jButtonBajaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaModificarActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaModificar);

        jButtonBajaConsultar.setText("CONSULTA");
        jButtonBajaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaConsultarActionPerformed(evt);
            }
        });
        jPanelNorteBaja.add(jButtonBajaConsultar);

        jPanelBaja.add(jPanelNorteBaja, java.awt.BorderLayout.NORTH);

        jLabelMatriculaBaja.setText("PON LA MATRICULA DEL VELERO QUE QUIERAS ELIMINAR : ");

        jTextFieldMatriculaBaja.setText("                                                    ");

        javax.swing.GroupLayout jPanelCentroBajaLayout = new javax.swing.GroupLayout(jPanelCentroBaja);
        jPanelCentroBaja.setLayout(jPanelCentroBajaLayout);
        jPanelCentroBajaLayout.setHorizontalGroup(
            jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                .addGroup(jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelMatriculaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jTextFieldMatriculaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelCentroBajaLayout.setVerticalGroup(
            jPanelCentroBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroBajaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelMatriculaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextFieldMatriculaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanelBaja.add(jPanelCentroBaja, java.awt.BorderLayout.CENTER);

        jButtonBajaAtras.setText("ATRAS");
        jButtonBajaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAtrasActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAtras);

        jButtonBajaAdelante.setText("ADELANTE");
        jButtonBajaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAdelanteActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAdelante);

        jButtonBajaAceptar.setText("ACEPTAR");
        jButtonBajaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaAceptarActionPerformed(evt);
            }
        });
        jPanelSurBaja.add(jButtonBajaAceptar);

        jPanelBaja.add(jPanelSurBaja, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelBaja, "card5");

        jPanelModificar.setLayout(new java.awt.BorderLayout());

        jButtonModificarAlta.setText("ALTA");
        jButtonModificarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAltaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarAlta);

        jButtonModificarBaja.setText("BAJA");
        jButtonModificarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarBajaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarBaja);

        jButtonModificarModificar.setText("MODIFICACION");
        jButtonModificarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarModificarActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarModificar);

        jButtonModificarConsulta.setText("CONSULTA");
        jButtonModificarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarConsultaActionPerformed(evt);
            }
        });
        jPanelNorteModificar.add(jButtonModificarConsulta);

        jPanelModificar.add(jPanelNorteModificar, java.awt.BorderLayout.NORTH);

        jLabelMatriculaModificar.setText("PON LA MATRICULA DEL VELERO QUE QUIERAS MODIFICAR : ");

        jTextFieldMatriculaModificar.setText("                                             ");

        javax.swing.GroupLayout jPanelCentroModificarLayout = new javax.swing.GroupLayout(jPanelCentroModificar);
        jPanelCentroModificar.setLayout(jPanelCentroModificarLayout);
        jPanelCentroModificarLayout.setHorizontalGroup(
            jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                .addGroup(jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelMatriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jTextFieldMatriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelCentroModificarLayout.setVerticalGroup(
            jPanelCentroModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroModificarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelMatriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jTextFieldMatriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jPanelModificar.add(jPanelCentroModificar, java.awt.BorderLayout.CENTER);

        jButtonModicarAtras.setText("ATRAS");
        jButtonModicarAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAtrasActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAtras);

        jButtonModicarAdelante.setText("ADELANTE");
        jButtonModicarAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAdelanteActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAdelante);

        jButtonModicarAceptar.setText("ACEPTAR");
        jButtonModicarAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModicarAceptarActionPerformed(evt);
            }
        });
        jPanelSurModificar.add(jButtonModicarAceptar);

        jPanelModificar.add(jPanelSurModificar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelModificar, "card4");

        jPanelConsulta.setLayout(new java.awt.BorderLayout());

        jButtonConsultaAlta.setText("ALTA");
        jButtonConsultaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAltaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaAlta);

        jButtonConsultaBaja.setText("BAJA");
        jButtonConsultaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaBajaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaBaja);

        jButtonConsultaModifcar.setText("MODIFICACION");
        jButtonConsultaModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaModifcarActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaModifcar);

        jButtonConsultaConsulta.setText("CONSULTA");
        jButtonConsultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaConsultaActionPerformed(evt);
            }
        });
        jPanelNorteConsulta.add(jButtonConsultaConsulta);

        jPanelConsulta.add(jPanelNorteConsulta, java.awt.BorderLayout.NORTH);

        jScrollPaneConsulta.setViewportView(jTextFieldConsulta);

        javax.swing.GroupLayout jPanelCentroConsultaLayout = new javax.swing.GroupLayout(jPanelCentroConsulta);
        jPanelCentroConsulta.setLayout(jPanelCentroConsultaLayout);
        jPanelCentroConsultaLayout.setHorizontalGroup(
            jPanelCentroConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroConsultaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelCentroConsultaLayout.setVerticalGroup(
            jPanelCentroConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelConsulta.add(jPanelCentroConsulta, java.awt.BorderLayout.CENTER);

        jButtonConsultaAtras.setText("ATRAS");
        jButtonConsultaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAtrasActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAtras);

        jButtonConsultaAdelante.setText("ADELANTE");
        jButtonConsultaAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAdelanteActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAdelante);

        jButtonConsultaAceptar.setText("ACEPTAR");
        jButtonConsultaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAceptarActionPerformed(evt);
            }
        });
        jPanelSurConsulta.add(jButtonConsultaAceptar);

        jPanelConsulta.add(jPanelSurConsulta, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelConsulta, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMatriculaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaAltaActionPerformed

    private void jTextFieldlDescripcionAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlDescripcionAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlDescripcionAltaActionPerformed

    private void jButtonAltaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());        
        cl.show(getContentPane(), "card6");           
    }//GEN-LAST:event_jButtonAltaAltaActionPerformed

    private void jButtonBajaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           

    }//GEN-LAST:event_jButtonBajaAltaActionPerformed

    private void jButtonModificarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           

    }//GEN-LAST:event_jButtonModificarAltaActionPerformed

    private void jButtonConsultaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAltaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card6");           
    }//GEN-LAST:event_jButtonConsultaAltaActionPerformed

    private void jButtonAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");           
        
    }//GEN-LAST:event_jButtonAltaBajaActionPerformed

    private void jButtonBajaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");           
    }//GEN-LAST:event_jButtonBajaBajaActionPerformed

    private void jButtonModificarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");                  
    }//GEN-LAST:event_jButtonModificarBajaActionPerformed

    private void jButtonConsultaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaBajaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card5");                  
    }//GEN-LAST:event_jButtonConsultaBajaActionPerformed

    private void jButtonAltaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonAltaModificarActionPerformed

    private void jButtonBajaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");                  
    }//GEN-LAST:event_jButtonBajaModificarActionPerformed

    private void jButtonModificarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarModificarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonModificarModificarActionPerformed

    private void jButtonConsultaModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaModifcarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card4");           
    }//GEN-LAST:event_jButtonConsultaModifcarActionPerformed

    private void jButtonAltaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonAltaConsultaActionPerformed

    private void jButtonBajaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaConsultarActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");           
    }//GEN-LAST:event_jButtonBajaConsultarActionPerformed

    private void jButtonModificarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonModificarConsultaActionPerformed

    private void jButtonConsultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaConsultaActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), "card3");                
    }//GEN-LAST:event_jButtonConsultaConsultaActionPerformed

    private void jButtonConsultaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonConsultaAtrasActionPerformed

    private void jButtonBajaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonBajaAtrasActionPerformed

    private void jButtonModicarAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonModicarAtrasActionPerformed

    private void jButtonAltaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAtrasActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
            cl.previous(getContentPane());//adelante
    }//GEN-LAST:event_jButtonAltaAtrasActionPerformed

    private void jButtonAltaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonAltaAdelanteActionPerformed

    private void jButtonBajaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonBajaAdelanteActionPerformed

    private void jButtonModicarAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonModicarAdelanteActionPerformed

    private void jButtonConsultaAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAdelanteActionPerformed
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.next(getContentPane());//adelante
    }//GEN-LAST:event_jButtonConsultaAdelanteActionPerformed
    //metodo añadir velero
    private void jButtonAltaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaAceptarActionPerformed
//        try{
//            //creamos objeto con sus parametros
//            String matricula = jTextFieldMatriculaAlta.getText();
//            String materialConstruccion = jTextFieldlMaterialConstruccionAlta.getText();
//            String descripcion = jTextFieldlMaterialConstruccionAlta.getText();
//            int eslora = Integer.parseInt(jTextFieldEsloraAlta.getText());
//            int manga = Integer.parseInt(jTextFieldMangaAlta.getText());
//            int puntal = Integer.parseInt(jTextFieldlPuntalAlta.getText());
//            int maxTripulacion = Integer.parseInt(jTextFieldTripulacionMaximaAlta.getText());
//            int año = Integer.parseInt(jTextFieldYearFabricacionAlta.getText());
//            int numMas = Integer.parseInt(jTextFieldNumMasAlta.getText());
//            String claseVelero = jTextFieldClaseVeleroAlta.getText();
//            Veleros velero = new Veleros(matricula, materialConstruccion, descripcion, eslora, manga, puntal, maxTripulacion, año, numMas, claseVelero);
//            if (cursor.darAltaVeleros(velero) != false) {
//                JOptionPane.showMessageDialog(this, "Velero añadido");
//            } else {
//                JOptionPane.showMessageDialog(this, "Velero no puede ser añadido");
//            }
//        } catch (NumberFormatException ex){
//        
//        }
    }//GEN-LAST:event_jButtonAltaAceptarActionPerformed
    //metodo borrar velero
    private void jButtonBajaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaAceptarActionPerformed
        try {
            //creamos objeto con sus parametros
            String matricula = jTextFieldMatriculaAlta.getText();
            Veleros velero = new Veleros(matricula);
            if (cursor.darBajaVeleros(velero) != false) {
                JOptionPane.showMessageDialog(this, "Velero borrado");
            } else {
                JOptionPane.showMessageDialog(this, "Velero no puede ser borrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "En estos momentos no se puede realizar la operacion");
        }
    }//GEN-LAST:event_jButtonBajaAceptarActionPerformed
    //metodo modificar velero
    private void jButtonModicarAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModicarAceptarActionPerformed
//        try {            
//            //creamos objeto con sus parametros
//            String matriculaViejo = jTextFieldMatriculaModificar.getText();
//            //creamos velero viejo
//            Veleros veleroViejo = new Veleros(matriculaViejo);
//            //creamos velero nuevo
//            String matricula = jTextFieldMatriculaAlta.getText();
//            String materialConstruccion = jTextFieldlMaterialConstruccionAlta.getText();
//            String descripcion = jTextFieldlMaterialConstruccionAlta.getText();
//            int eslora = Integer.parseInt(jTextFieldEsloraAlta.getText());
//            int manga = Integer.parseInt(jTextFieldMangaAlta.getText());
//            int puntal = Integer.parseInt(jTextFieldlPuntalAlta.getText());
//            int maxTripulacion = Integer.parseInt(jTextFieldTripulacionMaximaAlta.getText());
//            int año = Integer.parseInt(jTextFieldYearFabricacionAlta.getText());
//            int numMas = Integer.parseInt(jTextFieldNumMasAlta.getText());
//            String claseVelero = jTextFieldClaseVeleroAlta.getText();
//            Veleros veleroNuevo = new Veleros(matricula, materialConstruccion, descripcion, eslora, manga, puntal, maxTripulacion, año, numMas, claseVelero);
//            if (cursor.modificarVeleros(veleroNuevo, veleroViejo) != false) {
//                JOptionPane.showMessageDialog(this, "Velero modificado");
//            } else {
//                JOptionPane.showMessageDialog(this, "Velero no puede ser modificado");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "En estos momentos no se puede realizar la operacion");
//        }
    }//GEN-LAST:event_jButtonModicarAceptarActionPerformed
    //metodo consultar velero
    private void jButtonConsultaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAceptarActionPerformed
        Veleros velero = new Veleros(jTextFieldConsulta.getText());        
        //añadimos
        jTextFieldConsulta.setText(cursor.recorrerVeleros(velero));
        jScrollPaneConsulta.add(jTextFieldConsulta);
        jPanelCentroConsulta.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaAceptarActionPerformed

    private void jTextFieldlPuntalAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlPuntalAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlPuntalAltaActionPerformed

    private void jTextFieldTripulacionMaximaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTripulacionMaximaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTripulacionMaximaAltaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaAceptar;
    private javax.swing.JButton jButtonAltaAdelante;
    private javax.swing.JButton jButtonAltaAlta;
    private javax.swing.JButton jButtonAltaAtras;
    private javax.swing.JButton jButtonAltaBaja;
    private javax.swing.JButton jButtonAltaConsulta;
    private javax.swing.JButton jButtonAltaModificar;
    private javax.swing.JButton jButtonBajaAceptar;
    private javax.swing.JButton jButtonBajaAdelante;
    private javax.swing.JButton jButtonBajaAlta;
    private javax.swing.JButton jButtonBajaAtras;
    private javax.swing.JButton jButtonBajaBaja;
    private javax.swing.JButton jButtonBajaConsultar;
    private javax.swing.JButton jButtonBajaModificar;
    private javax.swing.JButton jButtonConsultaAceptar;
    private javax.swing.JButton jButtonConsultaAdelante;
    private javax.swing.JButton jButtonConsultaAlta;
    private javax.swing.JButton jButtonConsultaAtras;
    private javax.swing.JButton jButtonConsultaBaja;
    private javax.swing.JButton jButtonConsultaConsulta;
    private javax.swing.JButton jButtonConsultaModifcar;
    private javax.swing.JButton jButtonModicarAceptar;
    private javax.swing.JButton jButtonModicarAdelante;
    private javax.swing.JButton jButtonModicarAtras;
    private javax.swing.JButton jButtonModificarAlta;
    private javax.swing.JButton jButtonModificarBaja;
    private javax.swing.JButton jButtonModificarConsulta;
    private javax.swing.JButton jButtonModificarModificar;
    private javax.swing.JLabel jLabelClaseVeleroAlta;
    private javax.swing.JLabel jLabelDescripcionAlta;
    private javax.swing.JLabel jLabelEsloraAlta;
    private javax.swing.JLabel jLabelMangaAlta;
    private javax.swing.JLabel jLabelMaterialConstruccionAlta;
    private javax.swing.JLabel jLabelMatriculaAlta;
    private javax.swing.JLabel jLabelMatriculaBaja;
    private javax.swing.JLabel jLabelMatriculaModificar;
    private javax.swing.JLabel jLabelNumMasAlta;
    private javax.swing.JLabel jLabelPuntalAlta;
    private javax.swing.JLabel jLabelTripulacionMaximaAlta;
    private javax.swing.JLabel jLabelYearFabricacionAlta;
    private javax.swing.JPanel jPanelAlta;
    private javax.swing.JPanel jPanelBaja;
    private javax.swing.JPanel jPanelCentroAlta;
    private javax.swing.JPanel jPanelCentroBaja;
    private javax.swing.JPanel jPanelCentroConsulta;
    private javax.swing.JPanel jPanelCentroModificar;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JPanel jPanelNorteAlta;
    private javax.swing.JPanel jPanelNorteBaja;
    private javax.swing.JPanel jPanelNorteConsulta;
    private javax.swing.JPanel jPanelNorteModificar;
    private javax.swing.JPanel jPanelSurAlta;
    private javax.swing.JPanel jPanelSurBaja;
    private javax.swing.JPanel jPanelSurConsulta;
    private javax.swing.JPanel jPanelSurModificar;
    private javax.swing.JScrollPane jScrollPaneConsulta;
    private javax.swing.JTextField jTextFieldClaseVeleroAlta;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldEsloraAlta;
    private javax.swing.JTextField jTextFieldMangaAlta;
    private javax.swing.JTextField jTextFieldMatriculaAlta;
    private javax.swing.JTextField jTextFieldMatriculaBaja;
    private javax.swing.JTextField jTextFieldMatriculaModificar;
    private javax.swing.JTextField jTextFieldNumMasAlta;
    private javax.swing.JTextField jTextFieldTripulacionMaximaAlta;
    private javax.swing.JTextField jTextFieldYearFabricacionAlta;
    private javax.swing.JTextField jTextFieldlDescripcionAlta;
    private javax.swing.JTextField jTextFieldlMaterialConstruccionAlta;
    private javax.swing.JTextField jTextFieldlPuntalAlta;
    // End of variables declaration//GEN-END:variables
ImplementacionDAOVeleros cursor = new ImplementacionDAOVeleros();

}
