/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author user
 */
public class Alquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alquiler
     */
    public Alquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelDniClienteAlquiler = new javax.swing.JLabel();
        jTextFieldDniClienteAlquiler = new javax.swing.JTextField();
        jLabelFechaInicioAlquiler = new javax.swing.JLabel();
        jTextFieldFechaInicioAlquiler = new javax.swing.JTextField();
        jLabelFechaFinAlquiler = new javax.swing.JLabel();
        jTextFieldFechaFinAlquiler = new javax.swing.JTextField();
        jLabelTipoBarcoAlquiler = new javax.swing.JLabel();
        jTextFieldTipoBarcoAlquiler = new javax.swing.JTextField();
        jLabelMatriculaAlquiler = new javax.swing.JLabel();
        jTextFieldMatriculaAlquiler = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnviarAlquiler = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabelDniClienteAlquiler.setText("DNI CLIENTE");
        jPanel2.add(jLabelDniClienteAlquiler);

        jTextFieldDniClienteAlquiler.setText("                                                               ");
        jPanel2.add(jTextFieldDniClienteAlquiler);

        jLabelFechaInicioAlquiler.setText("FECHA INICIO ALQUILER");
        jPanel2.add(jLabelFechaInicioAlquiler);

        jTextFieldFechaInicioAlquiler.setText("                                                               ");
        jPanel2.add(jTextFieldFechaInicioAlquiler);

        jLabelFechaFinAlquiler.setText("FECHA FIN ALQUILER");
        jPanel2.add(jLabelFechaFinAlquiler);

        jTextFieldFechaFinAlquiler.setText("                                                               ");
        jPanel2.add(jTextFieldFechaFinAlquiler);

        jLabelTipoBarcoAlquiler.setText("PON TIPO BARCO");
        jPanel2.add(jLabelTipoBarcoAlquiler);

        jTextFieldTipoBarcoAlquiler.setText("                                                               ");
        jPanel2.add(jTextFieldTipoBarcoAlquiler);

        jLabelMatriculaAlquiler.setText("PON MATRICULA");
        jPanel2.add(jLabelMatriculaAlquiler);

        jTextFieldMatriculaAlquiler.setText("                                                               ");
        jPanel2.add(jTextFieldMatriculaAlquiler);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jButtonEnviarAlquiler.setText("ENVIAR ALQUILER");
        jPanel1.add(jButtonEnviarAlquiler);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarAlquiler;
    private javax.swing.JLabel jLabelDniClienteAlquiler;
    private javax.swing.JLabel jLabelFechaFinAlquiler;
    private javax.swing.JLabel jLabelFechaInicioAlquiler;
    private javax.swing.JLabel jLabelMatriculaAlquiler;
    private javax.swing.JLabel jLabelTipoBarcoAlquiler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDniClienteAlquiler;
    private javax.swing.JTextField jTextFieldFechaFinAlquiler;
    private javax.swing.JTextField jTextFieldFechaInicioAlquiler;
    private javax.swing.JTextField jTextFieldMatriculaAlquiler;
    private javax.swing.JTextField jTextFieldTipoBarcoAlquiler;
    // End of variables declaration//GEN-END:variables
}
