/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.io.DataInputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        coleccion = new ArrayList();
        fichero = new File("D:\\clientes.dat");
        cargarFichero();
    }
    
    public Clientes(String nombre,  int dni) {
        this.nombre = nombre;
        this.dni = dni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelDniCliente = new javax.swing.JLabel();
        jTextFieldDniCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonEnviarCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabelNombreCliente.setText("INTRODUCE NOMBRE CLIENTE");
        jPanel1.add(jLabelNombreCliente);

        jTextFieldNombreCliente.setText("                                              ");
        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreCliente);

        jLabelDniCliente.setText("INTRODUCE DNI CLIENTE");
        jPanel1.add(jLabelDniCliente);

        jTextFieldDniCliente.setText("                                           ");
        jPanel1.add(jTextFieldDniCliente);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButtonEnviarCliente.setText("ENVIAR");
        jButtonEnviarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEnviarCliente);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    private void jButtonEnviarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarClienteActionPerformed
        Clientes aux = new Clientes();
            int auxDni;
            aux.setNombre(jTextFieldNombreCliente.getText());
            auxDni = Integer.parseInt(jTextFieldDniCliente.getText());
            aux.setDni(auxDni);
            if (añadirCliente(aux))
                JOptionPane.showMessageDialog(this, "Cliente añadido con exito", "OK", 1);
        
        
    }//GEN-LAST:event_jButtonEnviarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarCliente;
    private javax.swing.JLabel jLabelDniCliente;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDniCliente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Clientes> coleccion;
    private File fichero;
    private String nombre;
    private int dni;
    
    //metodos
    public int userExists(Clientes cliente) {
        return coleccion.indexOf(cliente);
    }

    //cargar los datos del fihcero en la coleccion
    public void cargarFichero() {
        if (fichero.exists()) {//Si el archivo no existe no hace nada, asi que luego al guardar datos lo creara
            DataInputStream lector = null;
            try {//abrir el fichero para su lectura y carga
                lector = new DataInputStream(new FileInputStream(fichero));
                while (true) {
                    añadirCliente(new Clientes(lector.readUTF(), lector.readInt()));
                }
            } catch (EOFException ex) {
                System.out.println("Fichero ha sido leido");
            } catch (FileNotFoundException ex) {
                System.out.println("No se a ha encontrado el fichero");
            } catch (IOException ex) {
                System.out.println("Final del Archivo ");
            } finally {
                try {
                    lector.close();
                } catch (IOException ex) {
                    Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }
    
    public boolean añadirCliente(Clientes cliente) {
        int valido = userExists(cliente);
        if (valido == -1) {
            System.out.println("añadido");
            return coleccion.add(cliente);
        } else {
            return false;
        }
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setDni(int dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return nombre;
    }

    public int getDni() {
        return dni;
    }

}
