/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author user
 */
public class EmbarcacionesDeportivasMotor extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmbarcacionesDeportivasMotor
     */
    public EmbarcacionesDeportivasMotor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelMatriculaEmbarcacionesDeportivasMotor = new javax.swing.JLabel();
        jTextFieldMatriculaEmbarcacionesDeportivasMotor = new javax.swing.JTextField();
        jLabelEsloraEmbarcacionesDeportivasMotor = new javax.swing.JLabel();
        jTextFieldEsloraEmbarcacionesDeportivasMotor = new javax.swing.JTextField();
        jLabelYearFabricacionEmbarcacionesDeportivasMotor = new javax.swing.JLabel();
        jTextFieldYearFabricacionEmbarcacionesDeportivasMotor = new javax.swing.JTextField();
        jLabelPotenciaCVEmbarcacionesDeportivasMotor = new javax.swing.JLabel();
        jTextFieldPotenciaCVEmbarcacionesDeportivasMotor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnviarEmbarcacionesDeportivasMotor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabelMatriculaEmbarcacionesDeportivasMotor.setText("MATRICULA EMBARCACIONES");
        jPanel2.add(jLabelMatriculaEmbarcacionesDeportivasMotor);

        jTextFieldMatriculaEmbarcacionesDeportivasMotor.setText("                                                               ");
        jPanel2.add(jTextFieldMatriculaEmbarcacionesDeportivasMotor);

        jLabelEsloraEmbarcacionesDeportivasMotor.setText("ESLORA EMBARCACIONES");
        jPanel2.add(jLabelEsloraEmbarcacionesDeportivasMotor);

        jTextFieldEsloraEmbarcacionesDeportivasMotor.setText("                                                               ");
        jPanel2.add(jTextFieldEsloraEmbarcacionesDeportivasMotor);

        jLabelYearFabricacionEmbarcacionesDeportivasMotor.setText("AÑO FABRICACION EMBARCACIONES");
        jPanel2.add(jLabelYearFabricacionEmbarcacionesDeportivasMotor);

        jTextFieldYearFabricacionEmbarcacionesDeportivasMotor.setText("                                                               ");
        jPanel2.add(jTextFieldYearFabricacionEmbarcacionesDeportivasMotor);

        jLabelPotenciaCVEmbarcacionesDeportivasMotor.setText("POTENCIA CABALLOS EMBARCACIONES");
        jPanel2.add(jLabelPotenciaCVEmbarcacionesDeportivasMotor);

        jTextFieldPotenciaCVEmbarcacionesDeportivasMotor.setText("                                                               ");
        jPanel2.add(jTextFieldPotenciaCVEmbarcacionesDeportivasMotor);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jButtonEnviarEmbarcacionesDeportivasMotor.setText("ENVIAR EMBARCACION");
        jPanel1.add(jButtonEnviarEmbarcacionesDeportivasMotor);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarEmbarcacionesDeportivasMotor;
    private javax.swing.JLabel jLabelEsloraEmbarcacionesDeportivasMotor;
    private javax.swing.JLabel jLabelMatriculaEmbarcacionesDeportivasMotor;
    private javax.swing.JLabel jLabelPotenciaCVEmbarcacionesDeportivasMotor;
    private javax.swing.JLabel jLabelYearFabricacionEmbarcacionesDeportivasMotor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEsloraEmbarcacionesDeportivasMotor;
    private javax.swing.JTextField jTextFieldMatriculaEmbarcacionesDeportivasMotor;
    private javax.swing.JTextField jTextFieldPotenciaCVEmbarcacionesDeportivasMotor;
    private javax.swing.JTextField jTextFieldYearFabricacionEmbarcacionesDeportivasMotor;
    // End of variables declaration//GEN-END:variables
}
