/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author user
 */
public class Veleros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Veleros
     */
    public Veleros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelMatriculaVelero = new javax.swing.JLabel();
        jTextFieldMatriculaVelero = new javax.swing.JTextField();
        jLabelEsloraVelero = new javax.swing.JLabel();
        jTextFieldEsloraVelero = new javax.swing.JTextField();
        jLabelYearFabricacionVelero = new javax.swing.JLabel();
        jTextFieldYearFabricacionVelero = new javax.swing.JTextField();
        jLabelNumeroMastilesVelero = new javax.swing.JLabel();
        jTextFieldNumeroMastilesVelero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnviarVeleros = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabelMatriculaVelero.setText("MATRICULA VELERO");
        jPanel2.add(jLabelMatriculaVelero);

        jTextFieldMatriculaVelero.setText("                                                               ");
        jTextFieldMatriculaVelero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaVeleroActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMatriculaVelero);

        jLabelEsloraVelero.setText("ESLORA VELERO");
        jPanel2.add(jLabelEsloraVelero);

        jTextFieldEsloraVelero.setText("                                                               ");
        jTextFieldEsloraVelero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEsloraVeleroActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEsloraVelero);

        jLabelYearFabricacionVelero.setText("AÑO FABRICACION VELERO");
        jPanel2.add(jLabelYearFabricacionVelero);

        jTextFieldYearFabricacionVelero.setText("                                                               ");
        jPanel2.add(jTextFieldYearFabricacionVelero);

        jLabelNumeroMastilesVelero.setText("NUMERO MASTILES VELERO");
        jPanel2.add(jLabelNumeroMastilesVelero);

        jTextFieldNumeroMastilesVelero.setText("                                                               ");
        jPanel2.add(jTextFieldNumeroMastilesVelero);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButtonEnviarVeleros.setText("ENVIAR VELERO");
        jPanel1.add(jButtonEnviarVeleros);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMatriculaVeleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaVeleroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaVeleroActionPerformed

    private void jTextFieldEsloraVeleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEsloraVeleroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEsloraVeleroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarVeleros;
    private javax.swing.JLabel jLabelEsloraVelero;
    private javax.swing.JLabel jLabelMatriculaVelero;
    private javax.swing.JLabel jLabelNumeroMastilesVelero;
    private javax.swing.JLabel jLabelYearFabricacionVelero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEsloraVelero;
    private javax.swing.JTextField jTextFieldMatriculaVelero;
    private javax.swing.JTextField jTextFieldNumeroMastilesVelero;
    private javax.swing.JTextField jTextFieldYearFabricacionVelero;
    // End of variables declaration//GEN-END:variables
}
