/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author user
 */
public class Yates extends javax.swing.JInternalFrame {

    /**
     * Creates new form Yates
     */
    public Yates() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelEslora = new javax.swing.JLabel();
        jTextFieldEsloraYates = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMatriculaYate = new javax.swing.JTextField();
        jLabelYearFabricacion = new javax.swing.JLabel();
        jTextFieldYearFabricacionYate = new javax.swing.JTextField();
        jLabelPotenciaCV = new javax.swing.JLabel();
        jTextFieldPotenciaCaballosYate = new javax.swing.JTextField();
        jLabelNumeroCamarotes = new javax.swing.JLabel();
        jTextFieldNumeroCamarotesYate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnviarYate = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setLayout(new java.awt.GridLayout(5, 5));

        jLabelEslora.setText("ESLORA");
        jPanel2.add(jLabelEslora);

        jTextFieldEsloraYates.setText("                                                              ");
        jTextFieldEsloraYates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEsloraYatesActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEsloraYates);

        jLabelMatricula.setText("MATRICULA");
        jPanel2.add(jLabelMatricula);

        jTextFieldMatriculaYate.setText("                                                              ");
        jTextFieldMatriculaYate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaYateActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMatriculaYate);

        jLabelYearFabricacion.setText("AÑO FABRICACION");
        jPanel2.add(jLabelYearFabricacion);

        jTextFieldYearFabricacionYate.setText("                                                              ");
        jPanel2.add(jTextFieldYearFabricacionYate);

        jLabelPotenciaCV.setText("POTENCIA CABALLOS");
        jPanel2.add(jLabelPotenciaCV);

        jTextFieldPotenciaCaballosYate.setText("                                                              ");
        jPanel2.add(jTextFieldPotenciaCaballosYate);

        jLabelNumeroCamarotes.setText("NUMERO CAMAROTES");
        jPanel2.add(jLabelNumeroCamarotes);

        jTextFieldNumeroCamarotesYate.setText("                                                              ");
        jPanel2.add(jTextFieldNumeroCamarotesYate);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jButtonEnviarYate.setText("ENVIAR YATE");
        jPanel1.add(jButtonEnviarYate);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEsloraYatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEsloraYatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEsloraYatesActionPerformed

    private void jTextFieldMatriculaYateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaYateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaYateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarYate;
    private javax.swing.JLabel jLabelEslora;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNumeroCamarotes;
    private javax.swing.JLabel jLabelPotenciaCV;
    private javax.swing.JLabel jLabelYearFabricacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEsloraYates;
    private javax.swing.JTextField jTextFieldMatriculaYate;
    private javax.swing.JTextField jTextFieldNumeroCamarotesYate;
    private javax.swing.JTextField jTextFieldPotenciaCaballosYate;
    private javax.swing.JTextField jTextFieldYearFabricacionYate;
    // End of variables declaration//GEN-END:variables
}
